kind: GenericOperatorConfig
apiVersion: operator.openshift.io/v1alpha1
leaderElection:
  disable: true
interval: "30s"
storagePath: /tmp/insights-operator
endpoint: http://localhost:8081
recordHistory: true
historyPath: /tmp/insights-history
#impersonate: system:serviceaccount:openshift-insights:gather